### ISSUE TITLE
Any idea why the Vercel app is down? Why `pnpm`?

### ISSUE THREAD

**Issue by pranavr2003** [kitloong/nextjs-dashboard#21]
:( I wanted to have a look at a live preview before trying this out. 

Also, it doesn't seem like clicking any other menu item on the side menu is working. The hrefs are all pretty much `#`. Is there any reason why this is done in this theme?

I'm aware CoreUI's Nextjs template isn't free, so is this all a workaround to make it 'open-sourceable'?

**Comment by kitloong** [comment]
Hi @pranavr2003 

The app is not down, it is working as intended.
I have only set up the basic structure of the admin dashboard, with only login, register and a few pages for boilerplate use.

For the other components I mostly rely on the Bootstrap default styling, that's why the links from the sidebar are mostly not linkable.

Sorry for just dropping a link, but I believe this article explains pnpm better than I can
https://medium.com/pnpm/why-should-we-use-pnpm-75ca4bfe7d93

**Comment by pranavr2003** [comment]
@kitloong Sure, I understand. There's only one issue I'm facing now which is preventing me from using this boilerplate, and this is probably one of the many hassles you had faced in migrating to AppRouter. Each link on the dashboard, instead of routing back to `/`, seems to load infinitely. Is there any fix for this? 

PS I'm very new to React/NextJS. I'm an Angular guy but slowly trying to migrate my application to Next.

**Comment by pranavr2003** [comment]
@kitloong thanks. However, a few things aren't working. For instance, HeaderNotificationNav. When I register (based on what I understand from the code), it should login and show a notif on top saying "User registered". That doesn't work. Or am I getting the code wrong? I'm not a frontend guy btw, but I'm having to work with it atm

**Comment by kitloong** [comment]
Hi @pranavr2003 ,

The dashboard template serves as a static boilerplate, the mentioned feature is not implemented.

**Comment by pranavr2003** [comment]
Ah got it. Thanks
