### ISSUE TITLE
404 on api call

### ISSUE THREAD

**Issue by tongene** [kitloong/nextjs-dashboard#26]
This is a screenshot from the index page of the Pokemons client component. On the page which is a server component, the API call works correclty. Should the API in the Index component have this behaviour? It keeps returning a 404. In my case, when I try to fetch from supabase using the same functions, I actually get a 401 unauthorised error. Is there a reason an error pops up on the same component when calling an API?

![image](https://github.com/kitloong/nextjs-dashboard/assets/100230643/b256140c-2a8f-467c-9d1b-dbf2b3529734)

**Comment by kitloong** [comment]
Hi @tongene , thank you for reporting. 

I have the wrong URL on the `useSWR` that's why you will keep receiving 404 error.

If you get 401 most probably your API required your authentication.

I have implemented `useSWR` so that I could fetch the fresh data client side.

If you remove the `useSWR` and with some updates you could convert to a server component, feel free to update base on your need.

**Comment by tongene** [comment]
Ok. Thanks. You are right, the 401 went away after a few attempts to fix it.
